import random

listMovie = [
    {"Title":"Batman","Year":"1989","Rated":"PG-13","Released":"23 Jun 1989","Runtime":"126 min","Genre":"Action, Adventure","Director":"Tim Burton","Writer":"Bob Kane (Batman characters), Sam Hamm (story), Sam Hamm (screenplay), Warren Skaaren (screenplay)","Actors":"Michael Keaton, Jack Nicholson, Kim Basinger, Robert Wuhl","Plot":"The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.","Language":"English, French, Spanish","Country":"USA, UK","Awards":"Won 1 Oscar. Another 8 wins & 26 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},{"Source":"Rotten Tomatoes","Value":"72%"},{"Source":"Metacritic","Value":"69/100"}],"Metascore":"69","imdbRating":"7.5","imdbVotes":"325,041","imdbID":"tt0096895","Type":"movie","DVD":"25 Mar 1997","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
    {"Title":"Star Wars: Episode IV - A New Hope","Year":"1977","Rated":"PG","Released":"25 May 1977","Runtime":"121 min","Genre":"Action, Adventure, Fantasy, Sci-Fi","Director":"George Lucas","Writer":"George Lucas","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing","Plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 52 wins & 28 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"90/100"}],"Metascore":"90","imdbRating":"8.6","imdbVotes":"1,175,323","imdbID":"tt0076759","Type":"movie","DVD":"21 Sep 2004","BoxOffice":"N/A","Production":"20th Century Fox","Website":"N/A","Response":"True"},
    {'Title': 'El padrino', 'Year': '2004', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTI2MjI4NTgyNF5BMl5BanBnXkFtZTcwOTM5NzQ5MQ@@._V1_SX300.jpg', 'imdbRating': '4.8', 'Production': 'El Padrino LLC'}, 
    {'Title': 'El Padrino II: Border Intrusion', 'Year': '2011', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZmFhZDczZWUtZGMzZi00NWRlLWFhNmYtNDk4OGU2YjQ5MDJiXkEyXkFqcGdeQXVyMjIwMjIzODA@._V1_SX300.jpg', 'imdbRating': '5.6', 'Production': 'N/A'},  
    {'Title': 'Forrest Gump', 'Year': '1994', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'imdbRating': '8.8', 'Production': 'Paramount Pictures'}, 
    {'Title': 'Amanecer', 'Year': '2009', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjA2NDI0MTY1Ml5BMl5BanBnXkFtZTgwNDg3MzI3ODE@._V1_SX300.jpg', 'imdbRating': '8.4', 'Production': 'N/A'}, 
    {'Title': 'El Ciudadano Kramer', 'Year': '2013', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMzkxMzJlNDctNTNiMi00NjAyLTk3ZDctYjhiMzY4YzZhZGM1XkEyXkFqcGdeQXVyMTcxNTYyMjM@._V1_SX300.jpg', 'imdbRating': '4.9', 'Production': 'N/A'}, 
    {'Title': 'Casablanca', 'Year': '1942', 'Poster': 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'imdbRating': '8.5', 'Production': 'Warner Bros. Pictures'}, 
    {'Title': 'WALL·E', 'Year': '2008', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg', 'imdbRating': '8.4', 'Production': 'Walt Disney Pictures'}, 
    {'Title': 'Vértigo', 'Year': '1946', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWEzYzAxMmMtN2Y4Mi00MzM3LTg2MmUtZWVkNTMxMDIyYzlmXkEyXkFqcGdeQXVyMTk4MDgwNA@@._V1_SX300.jpg', 'imdbRating': '7.5', 'Production': 'N/A'}, 
    {'Title': 'Butch Cassidy', 'Year': '1973–1974', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWI2NjZiYTctZWFjMi00M2RjLTg0NTgtNGQzYmRhMGUxMDUxXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg', 'imdbRating': '6.9', 'Production': ''}, 
    {'Title': 'Terminator 2: Judgment Day', 'Year': '1991', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'imdbRating': '8.5', 'Production': 'TriStar Pictures'}, 
    {'Title': 'Papillon', 'Year': '1973', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZGRjZjQ0NzAtYmZlNS00Zjc1LTk1YWItMDY5YzQxMzA4MTAzXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg', 'imdbRating': '8.0', 'Production': 'Twentieth Century Fox Home Entertainment'}, 
    {'Title': 'Amadeus', 'Year': '1984', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg', 'imdbRating': '8.3', 'Production': 'Warner Bros. Pictures'}, 
    {'Title': 'JFK', 'Year': '1991', 'Poster': 'https://m.media-amazon.com/images/M/MV5BYjYyODExMDctZjgwYy00ZjQwLWI4OWYtOGFlYjA4ZjEzNmY1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'imdbRating': '8.0', 'Production': 'Warner Bros.'}, 
    {'Title': 'Taxi Driver', 'Year': '1976', 'Poster': 'https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'imdbRating': '8.3', 'Production': 'Columbia Pictures'}, 
    {'Title': 'Ben-Hur', 'Year': '1959', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNjgxY2JiZDYtZmMwOC00ZmJjLWJmODUtMTNmNWNmYWI5ODkwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'imdbRating': '8.1', 'Production': 'MGM'}, 
    {'Title': 'La loba', 'Year': '1965', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZmIyZjE1YjctMTAwYS00NjkwLTg5NTItYmRlMWQ1ZjhhMTY1XkEyXkFqcGdeQXVyNjUyMTgxNjA@._V1_SX300.jpg', 'imdbRating': '6.4', 'Production': 'N/A'}, 
    {'Title': 'Pacto de Sangre', 'Year': '2018–', 'Poster': 'https://m.media-amazon.com/images/M/MV5BYzkzODQ4OGUtM2EwZi00YjViLTlkZWUtNTI2YmRiYzcwOGJjXkEyXkFqcGdeQXVyMTcxNTYyMjM@._V1_SX300.jpg', 'imdbRating': '9.3', 'Production': ''}, 
    {'Title': 'Rocky', 'Year': '1976', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg', 'imdbRating': '8.1', 'Production': 'United Artists'}, 
    {'Title': 'Rio Bravo', 'Year': '1959', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZDVhMTk1NjUtYjc0OS00OTE1LTk1NTYtYWMzMDI5OTlmYzU2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'imdbRating': '8.0', 'Production': 'Xenon'}, 
    {'Title': 'La novicia rebelde', 'Year': '1971', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZDVhMDM5NTktNDhkNi00YWFhLTg3ZjgtODhkNTYwZDIwMDY4XkEyXkFqcGdeQXVyMzU0NzkwMDg@._V1_SX300.jpg', 'imdbRating': '7.0', 'Production': 'N/A'}, 
    {'Title': 'Heaven Knows, Mr. Allison', 'Year': '1957', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZjRmYTIwMGYtZWZmYy00MjY5LTkzOTgtMGQwMDdhMTdhMjEwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'imdbRating': '7.3', 'Production': 'Fox'}, 
    {'Title': 'Doctor Zhivago', 'Year': '1965', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNzdmZTk4MTktZmExNi00OWEwLTgxZDctNTE4NWMwNjc1Nzg2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'imdbRating': '8.0', 'Production': 'MGM'}, 
    {'Title': 'In a Lonely Place', 'Year': '1950', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNjRmZjcwZTQtYWY0ZS00ODAwLTg4YTktZDhlZDMwMTM1MGFkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'imdbRating': '8.0', 'Production': 'Columbia Pictures'}, 
    {'Title': 'Yellow Sky', 'Year': '1948', 'Poster': 'https://m.media-amazon.com/images/M/MV5BYjI1ZGQxMjYtYzQwOC00NmI0LTkwNGItOWY0NjllZDI1YTI5XkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg', 'imdbRating': '7.5', 'Production': '20th Century Fox Film Corporation'}, 
    {'Title': 'Shock Corridor', 'Year': '1963', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNTRhMjJkNjAtYTgwYy00YTc1LTgzMjItNDA3ZGI2NzM2YzNjXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg', 'imdbRating': '7.4', 'Production': 'Criterion Collection'}
]

def get_movie():
    movie_1 = random.choice(listMovie)
    while True:
        movie_2 = random.choice(listMovie)
        if movie_1 != movie_2: 
            break
    return movie_1, movie_2
